# Generated by Django 3.1.1 on 2020-09-09 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_introducetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('IntroduceTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.introducetitle')),
            ],
            options={
                'verbose_name_plural': 'Introductions',
            },
        ),
    ]
